// <auto-generated />
using System;
using HomeHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122211636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("HomeHub.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AreaSqFt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.HomeAmenity", b =>
                {
                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("TEXT");

                    b.HasKey("HomeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("HomeAmenities");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("HomeId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Home", b =>
                {
                    b.HasOne("HomeHub.Domain.Entities.Community", "Community")
                        .WithMany("Homes")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.HomeAmenity", b =>
                {
                    b.HasOne("HomeHub.Domain.Entities.Amenity", "Amenity")
                        .WithMany("HomeAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHub.Domain.Entities.Home", "Home")
                        .WithMany("HomeAmenities")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Lead", b =>
                {
                    b.HasOne("HomeHub.Domain.Entities.Community", "Community")
                        .WithMany("Leads")
                        .HasForeignKey("CommunityId");

                    b.HasOne("HomeHub.Domain.Entities.Home", "Home")
                        .WithMany("Leads")
                        .HasForeignKey("HomeId");

                    b.Navigation("Community");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("HomeAmenities");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Community", b =>
                {
                    b.Navigation("Homes");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("HomeHub.Domain.Entities.Home", b =>
                {
                    b.Navigation("HomeAmenities");

                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
